version: 2

 outputs:
    dev:
      database: "{{ env_var('PROJECT_ID', 'oasis-dwh-011h') }}"  # parameterize project for dbt runs based on environment variable with default project
      dataset: RAW_Constructive_System_TEMP
      

sources:
  - name: proyect_oasis
    schema: OASIS_Design_Proto
    tables: 
      - name: aux_component_type
      
      

     
  

